### ISSUE TITLE
The installer doesn't add the generated config to Git

### ISSUE THREAD

**Issue by spaze** [phpstan/extension-installer#10]
But that seems to be by design: https://github.com/phpstan/extension-installer/commit/c36c32c66319affdf6b4a838cbfe3afc7e20dca3

This causes a bit of a headache when the vendor dir is in Git as the `src/GeneratedConfig.php` file is `.gitignore`'d so it's not added, silently.

This should at least be documented (done in #11).

**Comment by ondrejmirtes** [comment]
Fixed by https://github.com/phpstan/extension-installer/commit/b9f4c4e9fe93373a102c982bda5b8e57f901ce33 and released as 1.0.2.
