### ISSUE TITLE
Evaluate drupol/composer-packages - A Composer helper classes for finding installed packages/types/installation directories

### ISSUE THREAD

**Issue by drupol** [phpstan/extension-installer#12]
Hi,

Recently I published a package that will help you find all the installed packages in your projects.

The [README](https://github.com/drupol/composer-packages/blob/master/README.md) file has examples on how to use it and more explanations on how it works.

The use case of this library is that I was looking for a way to retrieve all the installed packages directories. At first I was using symfony/finder, but it was heavy and very slow. Then, I had the idea to "cache" those data through a Composer plugin, this is how I had the idea of this package.

On top of adding functionalities to get the package directories, I did the same kind of stuff for the package types and for the packages themselves.

In this particular use case, you can use it to directly get packages of type 'phpstan-extension' just by using:

`Types::phpstanExtension();`
or
`Types::get('phpstan-extension');`

Feel free to test it, if you are going to use it in your project and let me know how it goes, feedback is appreciated.

Examples of class that this package will generate:
* https://paste.ee/p/yMpHF
* https://paste.ee/p/jFrfI
* https://paste.ee/p/mRa5B

Thanks!

**Comment by ondrejmirtes** [comment]
Hi, how is this related to this package? I’m sorry, but you should never do this. Write a blogpost, ask for feedback on Twitter and Reddit. That’s how I’ve been doing it for years.

**Comment by drupol** [comment]
Hi Ondrej,

Could you explain why this is not advised ?

FYI, the idea comes from this package https://github.com/Ocramius/PackageVersions

**Comment by ondrejmirtes** [comment]
You open an issue if you have a problem or an idea for improvement with this specific package. Not if you want advice or feedback with your unrelated work. If there’s something I didn’t see, please clarify as I don’t see any actionable info for myself.

**Comment by drupol** [comment]
Thanks, very helpful.

**Comment by drupol** [comment]
Hi,

For the record, we had a chat during the EU Fossa hackathon and I got the explanation.

Basically the idea is to lower the dependencies to the maximum for PHPStan and it's side packages.
