### ISSUE TITLE
Question: adding composer extra for should be a breaking change?

### ISSUE THREAD

**Issue by nunomaduro** [phpstan/extension-installer#2]
Thanks for this feature.

For phpstan extension developers, adding the `phpstan` extra key should be consider a breaking change? As we are going to auto-wire extensions and possible breaking people deployments?

**Comment by ondrejmirtes** [comment]
My thinking (this early in the development cycle) is that the ones that install `phpstan/extension-installer` really don't want to manage this too closely and just want the latest and greatest. Feel free to add neon files at any time.
