### ISSUE TITLE
Bug?: `composer update` removed the package

### ISSUE THREAD

**Issue by ThomasLandauer** [phpstan/extension-installer#25]
At the end of the `composer update` output I'm getting:
```
Symfony operations: 1 recipe (20dfc4e46c7b7d0a930db3febc76557f)
  - Unconfiguring phpstan/extension-installer (>=1.0.5): From auto-generated recipe
phpstan/extension-installer: Package not found (probably scheduled for removal); extensions installation skipped.
```
These are the versions I had before:
phpstan/extension-installer 1.0.5
phpstan/phpstan 0.12.43
phpstan/phpstan-deprecation-rules 0.12.5
phpstan/phpstan-doctrine 0.12.20
phpstan/phpstan-strict-rules 0.12.5
phpstan/phpstan-symfony 0.12.8

And these are the versions I have now (notice that `phpstan/extension-installer` is gone):
phpstan/phpstan 0.12.50
phpstan/phpstan-deprecation-rules 0.12.5
phpstan/phpstan-doctrine 0.12.21
phpstan/phpstan-strict-rules 0.12.5
phpstan/phpstan-symfony 0.12.9

**Comment by ondrejmirtes** [comment]
Hi, I guess this is some kind of Symfony Flex thing that I have no control over. I’d use a plain good old Composer without any magic, it definitely doesn’t uninstall packages for its own pleasure 😊

**Comment by ThomasLandauer** [comment]
Still trying to figure it out - see https://github.com/symfony/recipes/issues/834

**Comment by ondrejmirtes** [comment]
Subscribed, thanks for reporting it :)
