### ISSUE TITLE
Composer is trying to use extension-installer when using --no-dev flag 

### ISSUE THREAD

**Issue by simPod** [phpstan/extension-installer#3]
When using `--no-dev` flag, Composer still tries to work with Installer. However, when Installer is installed as dev dependency, there are no related files and Composer fails.

> file_put_contents(/<path>/vendor/phpstan/extension-installer/src/GeneratedConfig.php): failed to open stream: No such file or directory  

How to reproduce:
```sh
composer install
composer install --no-dev
```

**Comment by ondrejmirtes** [comment]
Do you have any solution or suggestion how to solve this? I'm not experiencing this because I only run `--no-dev` on a fresh clone and not following full `install`.
