### ISSUE TITLE
Drop composer plugin usage in favor of generating/use the config from phpstan directly

### ISSUE THREAD

**Issue by mvorisek** [phpstan/extension-installer#47]
Starting with composer 2.2 all plugins are disabled by default and manual confirmation to enable them is required.

This is a feature request to drop the config generation via composer plugin by generating the config from phpstan directly on runtime like:

```
if (class_exists(\PHPStan\ExtensionInstaller\GeneratedConfig::class)) {
    $config = \PHPStan\ExtensionInstaller\GeneratedConfig::getConfig();
    // add generated config to phpstan
    // ...
}
```

**Comment by ondrejmirtes** [comment]
This was already addressed in the README: https://github.com/phpstan/extension-installer/pull/41/files

I don't want to change how the plugin works.
