### ISSUE TITLE
Add ability to not install extensions

### ISSUE THREAD

**Issue by canvural** [phpstan/extension-installer#56]
Hi,

This is a know problem that you can't not enable a package if you install both the extension and extension installer. For example here: https://github.com/phpstan/phpstan-strict-rules#with-extension-installer I'd like to enable just couple of rules not the all of them.

What I'd like to suggest is the ability to not auto install some extensions. This can be done for example like so in users `composer.json`:

```json
"extra": {
    "phpstan": {
        "dont-install": [
            "phpstan/phpstan-strict-rules"
        ]
    }
}
```

So `phpstan/extension-installer` can check if this config exists in users `composer.json` and if the PHPStan extension is in the list, it'll not be automatically installed.

I got the idea from [Laravel.](https://laravel.com/docs/9.x/packages#opting-out-of-package-discovery) 

What do you think?

**Comment by ondrejmirtes** [comment]
I'd rather solve this with a nicer configuration in phpstan-strict-rules.

**Comment by canvural** [comment]
Ok. That's fine.
