### ISSUE TITLE
Is it possible to run this plugin manually?

### ISSUE THREAD

**Issue by enumag** [phpstan/extension-installer#6]
When dockerizing my application I first `COPY` just `composer.json` and `composer.lock`, then I have a `RUN` layer with `composer install` and only then copy the rest of the application. This is good for caching the layer with all the installed packages.

Unfortunately since I'm using `symfony/flex` I have to run `composer install` with `--no-scripts` because otherwise `flex` would fail when I don't have the application files yet (missing configuration for some bundles).

This of course disables `phpstan/extension-installer` as well so I'd like to run it manually somehow. Is there a way to do that?

**Comment by ondrejmirtes** [comment]
I don't know. If your needs don't match how the plugin works, you probably can't use it...

**Comment by enumag** [comment]
It would be possible to implement this. For example [vaimo/composer-patches](https://github.com/vaimo/composer-patches) has this feature - you can run the plugin's logic manually using `composer patch:apply`.

**Comment by ondrejmirtes** [comment]
Feel free to send a PR :)
