### ISSUE TITLE
Extension installer is also execute when not using phpstan

### ISSUE THREAD

**Issue by dvdknaap** [phpstan/extension-installer#77]
i've installed this plugin and somehow it's also running when i run my website outside phpstan.

when i install this package, i get an error that it cand find the PhpDocParser and that it needs to added to the use statement but it's already there.
vendor/symfony/property-info/Extractor/PhpStanExtractor.php on line 67

when i remove this package my website works again.

i've also added the includes again in the phpstan.neon file and phpstan is still working with the phpstan extensions

**Comment by ondrejmirtes** [comment]
Please create a small reproducing repository that shows the problem.
