### ISSUE TITLE
Question: Is there a way to list extensions?

### ISSUE THREAD

**Issue by earthiverse** [phpstan/extension-installer#82]
I am trying to add phpstan extension support to a few libraries we use internally, and am wondering if they're being detected / loaded correctly.

**Comment by ondrejmirtes** [comment]
After running `composer install` and similar the plugin outputs what extensions were installed.

If there's a package with `phpstan` in the name that does not support extension-installer, it's printed in yellow as "not installed".

**Comment by earthiverse** [comment]
@ondrejmirtes Perfect! Thank you so much!
