### ISSUE TITLE
(prod) error after updating to 1.4.0

### ISSUE THREAD

**Issue by pfpro** [phpstan/extension-installer#87]
Im using symfony 6.4 and phpstan and get an error on my prod environment:

_Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - phpstan/extension-installer is locked to version 1.4.0 and an update of this package was not requested.
    - phpstan/extension-installer 1.4.0 requires composer-plugin-api ^2.6.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint._

Can anyone do something with this?

**Comment by ondrejmirtes** [comment]
1) You shouldn't install dev dependencies in production environment at all, that't the first problem
2) 2nd problem is that you have too old Composer version in your production, install the latest one `composer self-update`
