### ISSUE TITLE
Question - 1.4.0 has dependency on composer-plugin-api v2.6.0+

### ISSUE THREAD

**Issue by vreemt** [phpstan/extension-installer#88]
Hi, I'm updating a drupal site and came across the following dependency issue

```
phpstan/extension-installer 1.4.0 requires composer-plugin-api ^2.6.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - drupal/core-dev 10.2.7 requires phpstan/extension-installer ^1.1 ->
```

I have limited access to composer/composer plugins on the target system (Pantheon, php 8.1), which is running `Composer version 2.5.8 2023-06-09 17:13:21`, my local system with an _older_ composer version (`2.5.5 2023-03-21 11:50:05`) doesn't have this issue

I tried adding a requirement for `composer-plugin-api:^2.6`, but it seems to insist on 2.3:
> Root composer.json requires composer-plugin-api ^2.6, found composer-plugin-api[2.3.0] but it does not match the constraint.

I searched the [documentation](https://phpstan.org/user-guide/extension-library#installing-extensions) and [site](https://phpstan.org/user-guide/backward-compatibility-promise), but didn't really find specifics around the composer plugin api.

For now, I'm using `composer require "phpstan/extension-installer:1.0 - 1.3" --dev`.

Is there any documentation around the version of `composer-plugin-api` for the extension installer? 

Thanks, Sandra.

**Comment by ondrejmirtes** [comment]
Hey, I just released phpstan/extension-installer 1.4.1 which rolls back the bump in `composer-plugin-api`, so it should be usable as 1.3.1 was.
