### ISSUE TITLE
Unable to user the lib after upgrade to PHPStan 2.0

### ISSUE THREAD

**Issue by rochamarcelo** [phpstan/extension-installer#90]
After the upgrade of PHPStan 2.0 I'm unable to run phpstan.

```
"cakedc/cakephp-phpstan": "^4.0",
"phpstan/extension-installer": "^1.4",
"phpstan/phpstan": "^2.0",
```
PS: I'm able to use the extension without phpstan/extension-installer

Full rrror:

Note: Using configuration file /app/phpstan.neon.
PHP Fatal error:  Uncaught _PHPStan_eb82cb2ad\Nette\InvalidArgumentException: Missing parameter 'featureToggles.narrowPregMatches'. in phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php:62
Stack trace:
#0 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand('%featureToggles...', Array, false)
#1 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array, false)
#2 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array, false)
#3 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array, false)
#4 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Extensions/ParametersExtension.php(39): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array)
#5 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(169): _PHPStan_eb82cb2ad\Nette\DI\Extensions\ParametersExtension->loadConfiguration()
#6 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(158): _PHPStan_eb82cb2ad\Nette\DI\Compiler->processExtensions()
#7 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(99): _PHPStan_eb82cb2ad\Nette\DI\Compiler->compile()
#8 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(65): _PHPStan_eb82cb2ad\Nette\DI\ContainerLoader->generate('Container_a063d...', Array)
#9 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(34): _PHPStan_eb82cb2ad\Nette\DI\ContainerLoader->loadFile('Container_a063d...', Array)
#10 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(71): _PHPStan_eb82cb2ad\Nette\DI\ContainerLoader->load(Array, Array)
#11 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(177): PHPStan\DependencyInjection\Configurator->loadContainer()
#12 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(164): _PHPStan_eb82cb2ad\Nette\Bootstrap\Configurator->createContainer(true)
#13 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php(103): PHPStan\DependencyInjection\Configurator->createContainer()
#14 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(282): PHPStan\DependencyInjection\ContainerFactory->create('/tmp/phpstan', Array, Array, Array, Array, '7', NULL, NULL)
#15 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(129): PHPStan\Command\CommandHelper::begin(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput), Array, NULL, NULL, Array, '/app/phpstan.ne...', NULL, '7', false, true, true)
#16 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_eb82cb2ad\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->doRun(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(114): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->run()
#21 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(115): _PHPStan_eb82cb2ad\{closure}()
#22 /app/vendor/phpstan/phpstan/phpstan(8): require('phar:///app/ven...')
#23 /app/vendor/bin/phpstan(119): include('/app/vendor/php...')
#24 {main}
  thrown in phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php on line 62
Fatal error: Uncaught _PHPStan_eb82cb2ad\Nette\InvalidArgumentException: Missing parameter 'featureToggles.narrowPregMatches'. in phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php:62
Stack trace:
#0 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand('%featureToggles...', Array, false)
#1 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array, false)
#2 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array, false)
#3 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php(34): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array, false)
#4 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Extensions/ParametersExtension.php(39): _PHPStan_eb82cb2ad\Nette\DI\Helpers::expand(Array, Array)
#5 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(169): _PHPStan_eb82cb2ad\Nette\DI\Extensions\ParametersExtension->loadConfiguration()
#6 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php(158): _PHPStan_eb82cb2ad\Nette\DI\Compiler->processExtensions()
#7 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(99): _PHPStan_eb82cb2ad\Nette\DI\Compiler->compile()
#8 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(65): _PHPStan_eb82cb2ad\Nette\DI\ContainerLoader->generate('Container_a063d...', Array)
#9 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php(34): _PHPStan_eb82cb2ad\Nette\DI\ContainerLoader->loadFile('Container_a063d...', Array)
#10 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(71): _PHPStan_eb82cb2ad\Nette\DI\ContainerLoader->load(Array, Array)
#11 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(177): PHPStan\DependencyInjection\Configurator->loadContainer()
#12 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php(164): _PHPStan_eb82cb2ad\Nette\Bootstrap\Configurator->createContainer(true)
#13 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php(103): PHPStan\DependencyInjection\Configurator->createContainer()
#14 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(282): PHPStan\DependencyInjection\ContainerFactory->create('/tmp/phpstan', Array, Array, Array, Array, '7', NULL, NULL)
#15 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(129): PHPStan\Command\CommandHelper::begin(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput), Array, NULL, NULL, Array, '/app/phpstan.ne...', NULL, '7', false, true, true)
#16 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_eb82cb2ad\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->doRun(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(114): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->run()
#21 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(115): _PHPStan_eb82cb2ad\{closure}()
#22 /app/vendor/phpstan/phpstan/phpstan(8): require('phar:///app/ven...')
#23 /app/vendor/bin/phpstan(119): include('/app/vendor/php...')
#24 {main}
  thrown in phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Helpers.php on line 62
Script phpstan analyse plugins/DigitalFacturas/src/ --debug handling the df-stan event returned with error code 255

**Comment by ondrejmirtes** [comment]
Please show me the output of your `composer install`.

**Comment by rochamarcelo** [comment]
```
fpm composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Package operations: 107 installs, 0 updates, 0 removals
  - Installing cakephp/plugin-installer (2.0.1): Extracting archive
  - Installing phpstan/phpstan (2.0.0): Extracting archive
  - Installing squizlabs/php_codesniffer (3.10.2): Extracting archive
  - Installing dealerdirect/phpcodesniffer-composer-installer (v1.0.0): Extracting archive
  - Installing phpstan/extension-installer (1.4.3): Extracting archive
  - Installing nikic/php-parser (v4.19.1): Extracting archive
  - Installing brick/varexporter (0.4.0): Extracting archive
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing psr/log (3.0.2): Extracting archive
  - Installing psr/http-message (2.0): Extracting archive
  - Installing psr/http-server-handler (1.0.2): Extracting archive
  - Installing psr/http-server-middleware (1.0.2): Extracting archive
  - Installing psr/http-factory (1.1.0): Extracting archive
  - Installing psr/http-client (1.0.3): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing league/container (4.2.4): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing guzzlehttp/psr7 (2.7.0): Extracting archive
  - Installing laminas/laminas-diactoros (3.5.0): Extracting archive
  - Installing laminas/laminas-httphandlerrunner (2.11.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.30.0): Extracting archive
  - Installing composer/ca-bundle (1.5.3): Extracting archive
  - Installing psr/clock (1.0.0): Extracting archive
  - Installing cakephp/chronos (3.1.0): Extracting archive
  - Installing cakephp/cakephp (5.1.2): Extracting archive
  - Installing cakedc/cakephp-db-test (3.0.1): Extracting archive
  - Installing cakedc/cakephp-phpstan (4.0.0): Extracting archive
  - Installing cakephp/authorization (3.2.0): Extracting archive
  - Installing cakephp/authentication (3.1.0): Extracting archive
  - Installing cakedc/auth (10.0.0): Extracting archive
  - Installing cakedc/users (14.2.1): Extracting archive
  - Installing phpstan/phpdoc-parser (1.29.1): Extracting archive
  - Installing slevomat/coding-standard (8.15.0): Extracting archive
  - Installing cakephp/cakephp-codesniffer (5.1.1): Extracting archive
  - Installing doctrine/sql-formatter (1.4.0): Extracting archive
  - Installing symfony/process (v7.1.3): Extracting archive
  - Installing symfony/polyfill-php81 (v1.30.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.30.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.30.0): Extracting archive
  - Installing symfony/finder (v7.1.3): Extracting archive
  - Installing symfony/polyfill-ctype (v1.30.0): Extracting archive
  - Installing symfony/filesystem (v7.1.2): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.30.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.30.0): Extracting archive
  - Installing symfony/string (v7.1.3): Extracting archive
  - Installing symfony/deprecation-contracts (v3.5.0): Extracting archive
  - Installing symfony/service-contracts (v3.5.0): Extracting archive
  - Installing symfony/console (v7.1.3): Extracting archive
  - Installing seld/signal-handler (2.0.2): Extracting archive
  - Installing seld/phar-utils (1.2.1): Extracting archive
  - Installing seld/jsonlint (1.11.0): Extracting archive
  - Installing react/promise (v3.2.0): Extracting archive
  - Installing justinrainbow/json-schema (5.3.0): Extracting archive
  - Installing composer/pcre (3.2.0): Extracting archive
  - Installing composer/xdebug-handler (3.0.5): Extracting archive
  - Installing composer/spdx-licenses (1.5.8): Extracting archive
  - Installing composer/semver (3.4.2): Extracting archive
  - Installing composer/metadata-minifier (1.0.0): Extracting archive
  - Installing composer/class-map-generator (1.3.4): Extracting archive
  - Installing composer/composer (2.7.7): Extracting archive
  - Installing cakephp/debug_kit (5.0.6): Extracting archive
  - Installing symfony/config (v7.1.1): Extracting archive
  - Installing robmorgan/phinx (0.16.2): Extracting archive
  - Installing cakephp/migrations (4.3.2): Extracting archive
  - Installing twig/twig (v3.10.3): Extracting archive
  - Installing twig/markdown-extra (v3.10.0): Extracting archive
  - Installing jasny/twig-extensions (v1.3.0): Extracting archive
  - Installing cakephp/twig-view (2.0.2): Extracting archive
  - Installing sebastian/diff (5.1.1): Extracting archive
  - Installing cakephp/bake (3.1.1): Extracting archive
  - Installing dereuromark/cakephp-ide-helper (2.2.4): Extracting archive
  - Installing friendsofcake/bootstrap-ui (5.0.1): Extracting archive
  - Installing guzzlehttp/promises (2.0.4): Extracting archive
  - Installing m1/env (2.2.0): Extracting archive
  - Installing josegonzalez/dotenv (4.0.0): Extracting archive
  - Installing seld/cli-prompt (1.0.4): Extracting archive
  - Installing league/climate (3.8.2): Extracting archive
  - Installing markstory/mini-asset (2.1.1): Extracting archive
  - Installing markstory/asset_compress (5.0.1): Extracting archive
  - Installing mobiledetect/mobiledetectlib (4.8.06): Extracting archive
  - Installing sebastian/version (4.0.1): Extracting archive
  - Installing sebastian/type (4.0.0): Extracting archive
  - Installing sebastian/recursion-context (5.0.0): Extracting archive
  - Installing sebastian/object-reflector (3.0.0): Extracting archive
  - Installing sebastian/object-enumerator (5.0.0): Extracting archive
  - Installing sebastian/global-state (6.0.2): Extracting archive
  - Installing sebastian/exporter (5.1.2): Extracting archive
  - Installing sebastian/environment (6.1.0): Extracting archive
  - Installing sebastian/comparator (5.0.1): Extracting archive
  - Installing sebastian/code-unit (2.0.0): Extracting archive
  - Installing sebastian/cli-parser (2.0.1): Extracting archive
  - Installing phpunit/php-timer (6.0.0): Extracting archive
  - Installing phpunit/php-text-template (3.0.1): Extracting archive
  - Installing phpunit/php-invoker (4.0.0): Extracting archive
  - Installing phpunit/php-file-iterator (4.1.0): Extracting archive
  - Installing theseer/tokenizer (1.2.3): Extracting archive
  - Installing sebastian/lines-of-code (2.0.2): Extracting archive
  - Installing sebastian/complexity (3.2.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (3.0.0): Extracting archive
  - Installing phpunit/php-code-coverage (10.1.15): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.4): Extracting archive
  - Installing myclabs/deep-copy (1.12.0): Extracting archive
  - Installing phpunit/phpunit (10.5.29): Extracting archive
  - Installing symfony/polyfill-uuid (v1.31.0): Extracting archive
  - Installing guzzlehttp/guzzle (7.9.2): Extracting archive
  - Installing uploadcare/uploadcare-php (v4.2.0): Extracting archive
Generating autoload files
64 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
> cakedc/cakephp-phpstan: installed
> composer/composer: installed
> composer/pcre: installed
> App\Console\Installer::postInstall

```

**Comment by ondrejmirtes** [comment]
This is caused by old version of `composer/pcre`. Update to at least 3.3.0.

**Comment by rochamarcelo** [comment]
Perfect, thank you.
